apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: udemy-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udemy-guestbook
      name: redis
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: redis
        image: redis
        labels:
          app: udemy-guestbook
          name: redis
        ports:
        - containerPort: 6379